name: avocado_ripeness_app
description: "avocado ripeness checker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  
  executorch_flutter: ^0.3.1
  camera: ^0.11.0+2
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.0
  image: ^4.1.7
  permission_handler: ^11.3.1
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_icons:
  ios: true
  image_path: "assets/images/launcher/Avocado_iOS.001.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "assets/images/launcher/Avocado_Android_Background.001.png"
  adaptive_icon_foreground: "assets/images/launcher/Avocado_Android_Foreground.001.png"

flutter_native_splash: 
  color: "#FFEABE"
  image: "assets/images/splash/Avocado_splash.png"
  android_12: 
    icon_background_color: "#FFEABE"
    image: "assets/images/splash/Avocado_splash.png"
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/models/
